"""Initial migration1

Revision ID: 17b8bca6aea6
Revises: 
Create Date: 2025-02-03 15:18:46.637073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b8bca6aea6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistical_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usetype', sa.String(length=50), nullable=False),
    sa.Column('qualified', sa.String(length=1), nullable=False),
    sa.Column('median_ratio', sa.Float(), nullable=False),
    sa.Column('aad', sa.Float(), nullable=False),
    sa.Column('cod', sa.Float(), nullable=False),
    sa.Column('n_val', sa.Integer(), nullable=False),
    sa.Column('mean_ratio', sa.Float(), nullable=False),
    sa.Column('weighted_mean_ratio', sa.Float(), nullable=False),
    sa.Column('std_deviation', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('cov', sa.Float(), nullable=False),
    sa.Column('prd', sa.Float(), nullable=False),
    sa.Column('prb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('syear', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('uploaded_file')
    op.drop_table('statistical_report')
    # ### end Alembic commands ###
